name: Build solution finder

on:
  push:
    branches: [ci*]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Build solution finder
        run: |
          cd solution-finder
          ./gradlew jar
          mv build/libs/solution-finder-*.jar ../solution-finder.jar
      - name: Install libluajit-5.1-dev
        run: sudo apt install libluajit-5.1-dev luajit
      - name: Build solution finder loader
        run: |
          jlink --add-modules java.base --output jre --no-man-pages --strip-debug --compress=2
          make build/Linux/sfinder.so JAVA_HOME=jre
      - name: Test
        run: |
          mkdir -p /lib/jvm
          ln -s $PWD/jre /lib/jvm/jre
          mkdir -p /lib/lua/5.1
          ln -s $PWD/build/Linux/sfinder.so /lib/lua/5.1/sfinder.so
          luajit test.lua solution-finder.jar
      - name: Create tarball
        run: |
          mv jre build/Linux/jre
          cd build/Linux
          tar -caf ../../Linux.tar.xz sfinder.so jre
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux.tar.xz
          path: Linux.tar.xz
      - name: Upload solution finder
        uses: actions/upload-artifact@v2
        with:
          name: solution-finder.jar
          path: solution-finder.jar
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            solution-finder.jar
            Linux.tar.xz
