name: Build solution finder

on:
  push:
    branches: [main, ci*]
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle
      - name: Build solution finder
        run: |
          cd solution-finder
          ./gradlew jar
          mv build/libs/solution-finder-*.jar ../solution-finder.jar
      - name: Install libluajit-5.1-dev
        run: sudo apt install libluajit-5.1-dev
      - name: Build solution finder loader
        run: |
          jlink --add-modules java.base --output jre --no-man-pages --strip-debug --compress=2
          make build/Linux/sfinder.so JAVA_HOME=jre
          mv jre build/Linux/jre
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: build/Linux
      - name: Upload solution finder
        uses: actions/upload-artifact@v2
        with:
          name: solution-finder
          path: solution-finder.jar
      - name: Pack build folder
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          7z a -tzip Linux.zip ./build/Linux/*
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            solution-finder.jar
            Linux.zip
